databases:
  - name: persona
    databaseName: persona_production
    user: persona_admin

services:
  - type: web
    name: persona
    env: ruby
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: persona
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
